// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7NWG0s-9Z8M5WeQgJq1mRuVY-6W8mVUw',
    appId: '1:854876175061:web:fce454e395448d9503805c',
    messagingSenderId: '854876175061',
    projectId: 'cropcompliance',
    authDomain: 'cropcompliance.firebaseapp.com',
    storageBucket: 'cropcompliance.firebasestorage.app',
    measurementId: 'G-WYCB8SGGQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKWlUuRI_a1DXx-j9GZ2106kGmWGrg87Q',
    appId: '1:854876175061:android:a826d41714b6b6ab03805c',
    messagingSenderId: '854876175061',
    projectId: 'cropcompliance',
    storageBucket: 'cropcompliance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEeZ71oGmCiTmjaDIeplsFxr0oNDU41WY',
    appId: '1:854876175061:ios:17ce1bf0e0cdea1a03805c',
    messagingSenderId: '854876175061',
    projectId: 'cropcompliance',
    storageBucket: 'cropcompliance.firebasestorage.app',
    iosBundleId: 'com.example.cropcompliance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEeZ71oGmCiTmjaDIeplsFxr0oNDU41WY',
    appId: '1:854876175061:ios:17ce1bf0e0cdea1a03805c',
    messagingSenderId: '854876175061',
    projectId: 'cropcompliance',
    storageBucket: 'cropcompliance.firebasestorage.app',
    iosBundleId: 'com.example.cropcompliance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7NWG0s-9Z8M5WeQgJq1mRuVY-6W8mVUw',
    appId: '1:854876175061:web:80af2ffbf87036c903805c',
    messagingSenderId: '854876175061',
    projectId: 'cropcompliance',
    authDomain: 'cropcompliance.firebaseapp.com',
    storageBucket: 'cropcompliance.firebasestorage.app',
    measurementId: 'G-SKJ8N05RNV',
  );

}